server:
  port: 8088
spring:
  datasource:
    url: 'r2dbc:h2:mem:///testdb;DB_CLOSE_DELAY=-1;'
    username: 'sa'
    password: ''
    driver-class-name: org.h2.Driver
  r2dbc:
    url: 'r2dbc:h2:mem:///testdb'
    username: 'sa'
    password: ''
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml
    default-schema: public
    liquibase-schema: public
